import uproot

def read_ntuple(file_path):
    with uproot.open(file_path + ":ge0/segments") as segments:
        
        #print("read all: ", segments.keys())

        events = segments.arrays(
            [   ############# sim ##############
                'me0_sim_track_id', 
                'me0_sim_track_type', 
                'me0_sim_track_charge', 
                'me0_sim_track_pt', 
                'me0_sim_track_phi', 
                'me0_sim_track_eta', 
                'me0_sim_track_energy', 
                'me0_sim_track_hit_index', 
                'me0_sim_hit_particle', 
                'me0_sim_hit_region', 
                'me0_sim_hit_chamber', 
                'me0_sim_hit_layer', 
                'me0_sim_hit_strip', 
                'me0_sim_hit_tof', 
                'me0_sim_hit_x', 
                'me0_sim_hit_y', 
                'me0_sim_hit_z', 
                'me0_sim_hit_r', 
                'me0_sim_hit_eta', 
                'me0_sim_hit_phi', 
                'me0_sim_hit_eta_partition', 
                'me0_sim_hit_trackid', 
                'me0_sim_hit_energyLoss', 
                'me0_sim_hit_pabs', 
                'me0_sim_hit_thetaAtEntry', 
                'me0_sim_hit_phiAtEntry', 
                'me0_sim_hit_processType', 
                'me0_sim_hit_digilink', 
                ############# digi ##############
                'me0_digi_hit_region', 
                'me0_digi_hit_chamber', 
                'me0_digi_hit_layer', 
                'me0_digi_hit_bx', 
                'me0_digi_hit_strip', 
                'me0_digi_hit_eta_partition',
                ############# rec ##############
                'me0_rec_hit_region', 
                'me0_rec_hit_chamber', 
                'me0_rec_hit_layer', 
                'me0_rec_hit_strip', 
                'me0_rec_hit_tof', 
                'me0_rec_hit_bx', 
                'me0_rec_hit_cluster_size', 
                'me0_rec_hit_x', 
                'me0_rec_hit_y', 
                'me0_rec_hit_z', 
                'me0_rec_hit_r', 
                'me0_rec_hit_eta', 
                'me0_rec_hit_phi', 
                'me0_rec_hit_eta_partition', 
                ############# seg ##############
                'me0_seg_region', 
                'me0_seg_chamber', 
                'me0_seg_nRecHits', 
                'me0_seg_deltaPhi', 
                'me0_seg_chi2', 
                'me0_seg_ndof', 
                'me0_seg_bunchX', 
                'me0_seg_origin_x',
                'me0_seg_origin_y', 
                'me0_seg_origin_z',
                'me0_seg_origin_r', 
                'me0_seg_origin_eta', 
                'me0_seg_origin_phi', 
                'me0_seg_dir_theta', 
                'me0_seg_dir_phi', 
                'me0_seg_param_dxdz', 
                'me0_seg_param_dydz', 
                'me0_seg_param_x', 
                'me0_seg_param_y', 
                'me0_seg_rec_hit_index'],
            
            aliases = {
                ############# sim ##############
                'me0_sim_track_id': "me0_sim_track_id",
                'me0_sim_track_type': "me0_sim_track_type", 
                'me0_sim_track_charge': "me0_sim_track_charge", 
                'me0_sim_track_pt': "me0_sim_track_pt", 
                'me0_sim_track_phi': "me0_sim_track_phi", 
                'me0_sim_track_eta': "me0_sim_track_eta", 
                'me0_sim_track_energy': "me0_sim_track_energy", 
                'me0_sim_track_hit_index': "me0_sim_track_hit_index", 
                'me0_sim_hit_particle': "me0_sim_hit_particle", 
                'me0_sim_hit_region': "me0_sim_hit_region", 
                'me0_sim_hit_chamber': "me0_sim_hit_chamber", 
                'me0_sim_hit_layer': "me0_sim_hit_layer", 
                'me0_sim_hit_strip': "me0_sim_hit_strip", 
                'me0_sim_hit_tof': "me0_sim_hit_tof", 
                'me0_sim_hit_x': "me0_sim_hit_x", 
                'me0_sim_hit_y': "me0_sim_hit_y", 
                'me0_sim_hit_z': "me0_sim_hit_z", 
                'me0_sim_hit_r': "me0_sim_hit_r", 
                'me0_sim_hit_eta': "me0_sim_hit_eta", 
                'me0_sim_hit_phi': "me0_sim_hit_phi", 
                'me0_sim_hit_eta_partition': "me0_sim_hit_eta_partition", 
                'me0_sim_hit_trackid': "me0_sim_hit_trackid", 
                'me0_sim_hit_energyLoss': "me0_sim_hit_energyLoss", 
                'me0_sim_hit_pabs': "me0_sim_hit_pabs", 
                'me0_sim_hit_thetaAtEntry': "me0_sim_hit_thetaAtEntry", 
                'me0_sim_hit_phiAtEntry': "me0_sim_hit_phiAtEntry", 
                'me0_sim_hit_processType': "me0_sim_hit_processType", 
                'me0_sim_hit_digilink': "me0_sim_hit_digilink", 
                ############# digi ##############
                'me0_digi_hit_region': "me0_digi_hit_region", 
                'me0_digi_hit_chamber': "me0_digi_hit_chamber", 
                'me0_digi_hit_layer': "me0_digi_hit_layer", 
                'me0_digi_hit_bx': "me0_digi_hit_bx", 
                'me0_digi_hit_strip': "me0_digi_hit_strip", 
                'me0_digi_hit_eta_partition': "me0_digi_hit_eta_partition", 
                ############# rec ##############
                'me0_rec_hit_region': "me0_rec_hit_region", 
                'me0_rec_hit_chamber': "me0_rec_hit_chamber", 
                'me0_rec_hit_layer': "me0_rec_hit_layer", 
                'me0_rec_hit_strip': "me0_rec_hit_strip", 
                'me0_rec_hit_tof': "me0_rec_hit_tof", 
                'me0_rec_hit_bx': "me0_rec_hit_bx", 
                'me0_rec_hit_cluster_size': "me0_rec_hit_cluster_size", 
                'me0_rec_hit_x': "me0_rec_hit_x", 
                'me0_rec_hit_y': "me0_rec_hit_y", 
                'me0_rec_hit_z': "me0_rec_hit_z", 
                'me0_rec_hit_r': "me0_rec_hit_r", 
                'me0_rec_hit_eta': "me0_rec_hit_eta", 
                'me0_rec_hit_phi': "me0_rec_hit_phi", 
                'me0_rec_hit_eta_partition': "me0_rec_hit_eta_partition", 
                ############# seg ##############
                'me0_seg_region': "me0_seg_region", 
                'me0_seg_chamber': "me0_seg_chamber", 
                'me0_seg_nRecHits': "me0_seg_nRecHits", 
                'me0_seg_deltaPhi': "me0_seg_deltaPhi", 
                'me0_seg_chi2': "me0_seg_chi2", 
                'me0_seg_ndof': "me0_seg_ndof", 
                'me0_seg_bunchX': "me0_seg_bunchX", 
                'me0_seg_origin_x': "me0_seg_origin_x", 
                'me0_seg_origin_y': "me0_seg_origin_y", 
                'me0_seg_origin_z': "me0_seg_origin_z", 
                'me0_seg_origin_r': "me0_seg_origin_r", 
                'me0_seg_origin_eta': "me0_seg_origin_eta", 
                'me0_seg_origin_phi': "me0_seg_origin_phi", 
                'me0_seg_dir_theta': "me0_seg_dir_theta", 
                'me0_seg_dir_phi': "me0_seg_dir_phi", 
                'me0_seg_param_dxdz': "me0_seg_param_dxdz", 
                'me0_seg_param_dydz': "me0_seg_param_dydz", 
                'me0_seg_param_x': "me0_seg_param_x", 
                'me0_seg_param_y': "me0_seg_param_y", 
                'me0_seg_rec_hit_index': "me0_seg_rec_hit_index"
            }
        )

    return events


