import uproot

def read_ntuple(file_path):
    with uproot.open(file_path + ":ge0/segments") as segments:
        
        #print("read all: ", segments.keys())

        events = segments.arrays(
            [   ############# sim ##############
                'me0_sim_track_id_i', 
                'me0_sim_track_type_i', 
                'me0_sim_track_charge_i', 
                'me0_sim_track_pt_i', 
                'me0_sim_track_phi_i', 
                'me0_sim_track_eta_i', 
                'me0_sim_track_energy_i', 
                'me0_sim_track_hit_index_i', 
                'me0_sim_hit_particle_i', 
                'me0_sim_hit_region_i', 
                'me0_sim_hit_chamber_i', 
                'me0_sim_hit_layer_i', 
                'me0_sim_hit_strip_i', 
                'me0_sim_hit_tof_i', 
                'me0_sim_hit_x_i', 
                'me0_sim_hit_y_i', 
                'me0_sim_hit_z_i', 
                'me0_sim_hit_r_i', 
                'me0_sim_hit_eta_i', 
                'me0_sim_hit_phi_i', 
                'me0_sim_hit_eta_partition_i', 
                'me0_sim_hit_trackid_i', 
                'me0_sim_hit_energyLoss_i', 
                'me0_sim_hit_pabs_i', 
                'me0_sim_hit_thetaAtEntry_i', 
                'me0_sim_hit_phiAtEntry_i', 
                'me0_sim_hit_processType_i', 
                'me0_sim_hit_digilink_i', 
                ############# digi ##############
                'me0_digi_hit_region_i', 
                'me0_digi_hit_chamber_i', 
                'me0_digi_hit_layer_i', 
                'me0_digi_hit_bx_i', 
                'me0_digi_hit_strip_i', 
                'me0_digi_hit_eta_partition_i',
                ############# rec ##############
                'me0_rec_hit_region_i', 
                'me0_rec_hit_chamber_i', 
                'me0_rec_hit_layer_i', 
                'me0_rec_hit_strip_i', 
                'me0_rec_hit_tof_i', 
                'me0_rec_hit_bx_i', 
                'me0_rec_hit_cluster_size_i', 
                'me0_rec_hit_x_i', 
                'me0_rec_hit_y_i', 
                'me0_rec_hit_z_i', 
                'me0_rec_hit_r_i', 
                'me0_rec_hit_eta_i', 
                'me0_rec_hit_phi_i', 
                'me0_rec_hit_eta_partition_i', 
                ############# seg ##############
                'me0_seg_region_i', 
                'me0_seg_chamber_i', 
                'me0_seg_nRecHits_i', 
                'me0_seg_deltaPhi_i', 
                'me0_seg_chi2_i', 
                'me0_seg_ndof_i', 
                'me0_seg_bunchX_i', 
                'me0_seg_origin_x_i',
                'me0_seg_origin_y_i', 
                'me0_seg_origin_z_i',
                'me0_seg_origin_r_i', 
                'me0_seg_origin_eta_i', 
                'me0_seg_origin_phi_i', 
                'me0_seg_dir_theta_i', 
                'me0_seg_dir_phi_i', 
                'me0_seg_param_dxdz_i', 
                'me0_seg_param_dydz_i', 
                'me0_seg_param_x_i', 
                'me0_seg_param_y_i', 
                'me0_seg_rec_hit_index_i'],
            
            aliases = {
                ############# sim ##############
                'me0_sim_track_id_i': "me0_sim_track_id",
                'me0_sim_track_type_i': "me0_sim_track_type", 
                'me0_sim_track_charge_i': "me0_sim_track_charge", 
                'me0_sim_track_pt_i': "me0_sim_track_pt", 
                'me0_sim_track_phi_i': "me0_sim_track_phi", 
                'me0_sim_track_eta_i': "me0_sim_track_eta", 
                'me0_sim_track_energy_i': "me0_sim_track_energy", 
                'me0_sim_track_hit_index_i': "me0_sim_track_hit_index", 
                'me0_sim_hit_particle_i': "me0_sim_hit_particle", 
                'me0_sim_hit_region_i': "me0_sim_hit_region", 
                'me0_sim_hit_chamber_i': "me0_sim_hit_chamber", 
                'me0_sim_hit_layer_i': "me0_sim_hit_layer", 
                'me0_sim_hit_strip_i': "me0_sim_hit_strip", 
                'me0_sim_hit_tof_i': "me0_sim_hit_tof", 
                'me0_sim_hit_x_i': "me0_sim_hit_x", 
                'me0_sim_hit_y_i': "me0_sim_hit_y", 
                'me0_sim_hit_z_i': "me0_sim_hit_z", 
                'me0_sim_hit_r_i': "me0_sim_hit_r", 
                'me0_sim_hit_eta_i': "me0_sim_hit_eta", 
                'me0_sim_hit_phi_i': "me0_sim_hit_phi", 
                'me0_sim_hit_eta_partition_i': "me0_sim_hit_eta_partition", 
                'me0_sim_hit_trackid_i': "me0_sim_hit_trackid", 
                'me0_sim_hit_energyLoss_i': "me0_sim_hit_energyLoss", 
                'me0_sim_hit_pabs_i': "me0_sim_hit_pabs", 
                'me0_sim_hit_thetaAtEntry_i': "me0_sim_hit_thetaAtEntry", 
                'me0_sim_hit_phiAtEntry_i': "me0_sim_hit_phiAtEntry", 
                'me0_sim_hit_processType_i': "me0_sim_hit_processType", 
                'me0_sim_hit_digilink_i': "me0_sim_hit_digilink", 
                ############# digi ##############
                'me0_digi_hit_region_i': "me0_digi_hit_region", 
                'me0_digi_hit_chamber_i': "me0_digi_hit_chamber", 
                'me0_digi_hit_layer_i': "me0_digi_hit_layer", 
                'me0_digi_hit_bx_i': "me0_digi_hit_bx", 
                'me0_digi_hit_strip_i': "me0_digi_hit_strip", 
                'me0_digi_hit_eta_partition_i': "me0_digi_hit_eta_partition", 
                ############# rec ##############
                'me0_rec_hit_region_i': "me0_rec_hit_region", 
                'me0_rec_hit_chamber_i': "me0_rec_hit_chamber", 
                'me0_rec_hit_layer_i': "me0_rec_hit_layer", 
                'me0_rec_hit_strip_i': "me0_rec_hit_strip", 
                'me0_rec_hit_tof_i': "me0_rec_hit_tof", 
                'me0_rec_hit_bx_i': "me0_rec_hit_bx", 
                'me0_rec_hit_cluster_size_i': "me0_rec_hit_cluster_size", 
                'me0_rec_hit_x_i': "me0_rec_hit_x", 
                'me0_rec_hit_y_i': "me0_rec_hit_y", 
                'me0_rec_hit_z_i': "me0_rec_hit_z", 
                'me0_rec_hit_r_i': "me0_rec_hit_r", 
                'me0_rec_hit_eta_i': "me0_rec_hit_eta", 
                'me0_rec_hit_phi_i': "me0_rec_hit_phi", 
                'me0_rec_hit_eta_partition_i': "me0_rec_hit_eta_partition", 
                ############# seg ##############
                'me0_seg_region_i': "me0_seg_region", 
                'me0_seg_chamber_i': "me0_seg_chamber", 
                'me0_seg_nRecHits_i': "me0_seg_nRecHits", 
                'me0_seg_deltaPhi_i': "me0_seg_deltaPhi", 
                'me0_seg_chi2_i': "me0_seg_chi2", 
                'me0_seg_ndof_i': "me0_seg_ndof", 
                'me0_seg_bunchX_i': "me0_seg_bunchX", 
                'me0_seg_origin_x_i': "me0_seg_origin_x", 
                'me0_seg_origin_y_i': "me0_seg_origin_y", 
                'me0_seg_origin_z_i': "me0_seg_origin_z", 
                'me0_seg_origin_r_i': "me0_seg_origin_r", 
                'me0_seg_origin_eta_i': "me0_seg_origin_eta", 
                'me0_seg_origin_phi_i': "me0_seg_origin_phi", 
                'me0_seg_dir_theta_i': "me0_seg_dir_theta", 
                'me0_seg_dir_phi_i': "me0_seg_dir_phi", 
                'me0_seg_param_dxdz_i': "me0_seg_param_dxdz", 
                'me0_seg_param_dydz_i': "me0_seg_param_dydz", 
                'me0_seg_param_x_i': "me0_seg_param_x", 
                'me0_seg_param_y_i': "me0_seg_param_y", 
                'me0_seg_rec_hit_index_i': "me0_seg_rec_hit_index"
            }
        )

    return events


