---

name: "CI"
on:
  pull_request:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master

jobs:

  behavioral:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        behs:
          - road/tb/subfunc.py
          - road/tb/pat_unit_beh.py
          - road/tb/pat_unit_mux_beh.py
          - road/tb/partition_beh.py
          - road/tb/analysis_mc.py
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Test Behaviors
        run: pytest ${{ matrix.behs }}

  cocotb:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        testbenches:
          - road/tb/test_mult.py
          - road/tb/test_fit.py
          - road/tb/test_pat_unit.py
          - road/tb/test_pat_unit_mux.py
          - road/tb/test_partition.py
          - road/tb/test_chamber.py
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Test Firmware Module
        run: python ${{ matrix.testbenches }}
